---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: cloud-refresh-petclinic
  labels:
    app: petclinic
spec:
  selector:
    matchLabels:
      app: petclinic
  replicas: 2
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: ttl.sh/kyle-boxboat/spring-petclinic@sha256:bb2ac7f08d6a04a6f40fafa2a69fe3f3c9bdb3929b56dd37406308c639bb5255
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 512Mi
              cpu: 100m
            limits:
              memory: 1024Mi
              cpu: 1000m
